import { ApplicationSource } from './application-source.enum';
import { ApplicationStatus } from './application-status.enum';

/**
 * Optional links related to an application
 * Based on DOMAIN.md section 2.3
 */
export interface ApplicationLinks {
  jobPostingUrl?: string;
  companyWebsiteUrl?: string;
  resumeUrl?: string;
  coverLetterUrl?: string;
}

/**
 * Next action/reminder for an application
 * Based on DOMAIN.md section 2.4
 */
export interface NextAction {
  date: string; // ISO date
  note?: string; // max 300 characters
  done?: boolean; // default false
}

/**
 * Job application entity
 * Based on DOMAIN.md section 2.2
 * 
 * Represents a job application with all necessary information
 * for tracking (company, status, salary, reminders, etc.)
 */
export type EmploymentType = 'CDI' | 'CDD' | 'INTERNSHIP' | 'ALTERNANCE' | 'FREELANCE';
export type SalaryPeriod = 'ANNUAL' | 'MONTHLY';

export const EmploymentTypeLabels: Record<EmploymentType, string> = {
  CDI: 'CDI',
  CDD: 'CDD',
  INTERNSHIP: 'Stage',
  ALTERNANCE: 'Alternance',
  FREELANCE: 'Freelance'
};

export const SalaryPeriodLabels: Record<SalaryPeriod, string> = {
  ANNUAL: 'Annuel',
  MONTHLY: 'Mensuel'
};

export interface Application {
  id: string;
  userId: string;
  companyName: string;
  companyDomain?: string;
  roleTitle: string;
  city?: string;
  country?: string;
  source: ApplicationSource;
  status: ApplicationStatus;
  employmentType?: EmploymentType;
  appliedDate?: string;
  salary?: number;
  currency?: string;
  salaryPeriod?: SalaryPeriod;
  tags?: string[];
  links?: ApplicationLinks;
  notes?: string;
  nextAction?: NextAction;
  createdAt: string;
  updatedAt: string;
}

/**
 * DTO for creating a new application
 * Does not contain id, userId, createdAt, updatedAt (generated by backend)
 */
export interface CreateApplicationDto {
  companyName: string;
  companyDomain?: string;
  roleTitle: string;
  city?: string;
  country?: string;
  source: ApplicationSource;
  status?: ApplicationStatus;
  employmentType?: EmploymentType;
  appliedDate?: string;
  salary?: number;
  currency?: string;
  salaryPeriod?: SalaryPeriod;
  tags?: string[];
  links?: ApplicationLinks;
  notes?: string;
  nextAction?: NextAction;
}

/**
 * DTO for updating an application
 * All fields are optional (patch update)
 * userId cannot be modified
 */
export interface UpdateApplicationDto {
  companyName?: string;
  companyDomain?: string;
  roleTitle?: string;
  city?: string;
  country?: string;
  source?: ApplicationSource;
  status?: ApplicationStatus;
  employmentType?: EmploymentType;
  appliedDate?: string;
  salary?: number;
  currency?: string;
  salaryPeriod?: SalaryPeriod;
  tags?: string[];
  links?: ApplicationLinks;
  notes?: string;
  nextAction?: NextAction;
}

// const app: Application = {
//     id: '123',
//     userId: 'user-456',
//     companyName: 'Tech Company',
//     roleTitle: 'Software Engineer',
//     city: 'Paris',
//     country: 'France',
//     source: ApplicationSource.LINKEDIN,
//     status: ApplicationStatus.APPLIED,
//     appliedDate: '2024-06-01',
//     salary: 60000,
//     currency: 'EUR',
//     tags: ['JavaScript', 'Remote'],
//     links: {
//         jobPostingUrl: 'https://linkedin.com/job-posting',
//         companyWebsiteUrl: 'https://techcompany.com',
//         resumeUrl: 'https://myresume.com/resume.pdf'
//     },
//     notes: 'Applied via LinkedIn. Waiting for response.',
//     nextAction: {
//         date: '2024-06-15',
//         note: 'Follow up if no response by this date.'
//     },
//     createdAt: new Date().toISOString(),
//     updatedAt: new Date().toISOString() 
// }
