import { ApplicationSource } from './application-source.enum';
import { ApplicationStatus } from './application-status.enum';

/**
 * Optional links related to an application
 * Based on DOMAIN.md section 2.3
 */
export interface ApplicationLinks {
  jobPostingUrl?: string;
  companyWebsiteUrl?: string;
  resumeUrl?: string;
  coverLetterUrl?: string;
}

/**
 * Next action/reminder for an application
 * Based on DOMAIN.md section 2.4
 */
export interface NextAction {
  date: string; // ISO date
  note?: string; // max 300 characters
  done?: boolean; // default false
}

/**
 * Job application entity
 * Based on DOMAIN.md section 2.2
 * 
 * Represents a job application with all necessary information
 * for tracking (company, status, salary, reminders, etc.)
 */
export interface Application {
  id: string;
  userId: string;
  companyName: string; // required, 1..120 characters
  roleTitle: string; // required, 1..120 characters
  location?: string; // optional, 0..120 (e.g., "Paris", "Remote")
  source: ApplicationSource;
  status: ApplicationStatus;
  appliedDate?: string; // ISO date (YYYY-MM-DD)
  salary?: number; // >= 0
  currency?: string; // default "EUR"
  tags?: string[]; // max 10 tags, each 1..30 characters
  links?: ApplicationLinks;
  notes?: string; // max 5000 characters
  nextAction?: NextAction;
  createdAt: string; // ISO date-time
  updatedAt: string; // ISO date-time
}

/**
 * DTO for creating a new application
 * Does not contain id, userId, createdAt, updatedAt (generated by backend)
 */
export interface CreateApplicationDto {
  companyName: string;
  roleTitle: string;
  location?: string;
  source: ApplicationSource;
  status?: ApplicationStatus; // default APPLIED if not provided
  appliedDate?: string;
  salary?: number;
  currency?: string;
  tags?: string[];
  links?: ApplicationLinks;
  notes?: string;
  nextAction?: NextAction;
}

/**
 * DTO for updating an application
 * All fields are optional (patch update)
 * userId cannot be modified
 */
export interface UpdateApplicationDto {
  companyName?: string;
  roleTitle?: string;
  location?: string;
  source?: ApplicationSource;
  status?: ApplicationStatus;
  appliedDate?: string;
  salary?: number;
  currency?: string;
  tags?: string[];
  links?: ApplicationLinks;
  notes?: string;
  nextAction?: NextAction;
}

// const app: Application = {
//     id: '123',
//     userId: 'user-456',
//     companyName: 'Tech Company',
//     roleTitle: 'Software Engineer',
//     location: 'Paris',
//     source: ApplicationSource.LINKEDIN,
//     status: ApplicationStatus.APPLIED,
//     appliedDate: '2024-06-01',
//     salaryMin: 50000,
//     salaryMax: 70000,
//     currency: 'EUR',
//     tags: ['JavaScript', 'Remote'],
//     links: {
//         jobPostingUrl: 'https://linkedin.com/job-posting',
//         companyWebsiteUrl: 'https://techcompany.com',
//         resumeUrl: 'https://myresume.com/resume.pdf'
//     },
//     notes: 'Applied via LinkedIn. Waiting for response.',
//     nextAction: {
//         date: '2024-06-15',
//         note: 'Follow up if no response by this date.'
//     },
//     createdAt: new Date().toISOString(),
//     updatedAt: new Date().toISOString() 
// }
