version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: candidex-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: candidex
    volumes:
      - candidex-mongo-data:/data/db
    networks:
      - candidex-network

volumes:
  candidex-mongo-data:
    driver: local

networks:
  candidex-network:
    driver: bridge
